'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute()>
<Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("NorthwindModel", "FK_Products_Categories", "Categories", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(NorthwindModel.Categories), "Products", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(NorthwindModel.Products))>

' Original file name:
' Generation date: 5/2/2011 3:59:22 PM
Namespace NorthwindModel

	''' <summary>
	''' There are no comments for NorthwindEntities in the schema.
	''' </summary>
	Partial Public Class NorthwindEntities
		Inherits System.Data.Objects.ObjectContext
		''' <summary>
		''' Initializes a new NorthwindEntities object using the connection string found in the 'NorthwindEntities' section of the application configuration file.
		''' </summary>
		Public Sub New()
			MyBase.New("name=NorthwindEntities", "NorthwindEntities")
			Me.OnContextCreated()
		End Sub
		''' <summary>
		''' Initialize a new NorthwindEntities object.
		''' </summary>
		Public Sub New(ByVal connectionString As String)
			MyBase.New(connectionString, "NorthwindEntities")
			Me.OnContextCreated()
		End Sub
		''' <summary>
		''' Initialize a new NorthwindEntities object.
		''' </summary>
		Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
			MyBase.New(connection, "NorthwindEntities")
			Me.OnContextCreated()
		End Sub
		Partial Private Sub OnContextCreated()
		End Sub
		''' <summary>
		''' There are no comments for Categories in the schema.
		''' </summary>
		Public ReadOnly Property Categories() As Global.System.Data.Objects.ObjectQuery(Of Categories)
			Get
				If (Me._Categories Is Nothing) Then
					Me._Categories = MyBase.CreateQuery(Of Categories)("[Categories]")
				End If
				Return Me._Categories
			End Get
		End Property
		Private _Categories As Global.System.Data.Objects.ObjectQuery(Of Categories)
		''' <summary>
		''' There are no comments for Products in the schema.
		''' </summary>
		Public ReadOnly Property Products() As Global.System.Data.Objects.ObjectQuery(Of Products)
			Get
				If (Me._Products Is Nothing) Then
					Me._Products = MyBase.CreateQuery(Of Products)("[Products]")
				End If
				Return Me._Products
			End Get
		End Property
		Private _Products As Global.System.Data.Objects.ObjectQuery(Of Products)
		''' <summary>
		''' There are no comments for Categories in the schema.
		''' </summary>
		Public Sub AddToCategories(ByVal categories As Categories)
			MyBase.AddObject("Categories", categories)
		End Sub
		''' <summary>
		''' There are no comments for Products in the schema.
		''' </summary>
		Public Sub AddToProducts(ByVal products As Products)
			MyBase.AddObject("Products", products)
		End Sub
	End Class
	''' <summary>
	''' There are no comments for NorthwindModel.Categories in the schema.
	''' </summary>
	''' <KeyProperties>
	''' CategoryID
	''' </KeyProperties>
	<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName := "NorthwindModel", Name := "Categories"), Global.System.Runtime.Serialization.DataContractAttribute(IsReference := True), Global.System.Serializable()> _
	Partial Public Class Categories
		Inherits System.Data.Objects.DataClasses.EntityObject
		''' <summary>
		''' Create a new Categories object.
		''' </summary>
		''' <param name="categoryID">Initial value of CategoryID.</param>
		''' <param name="categoryName">Initial value of CategoryName.</param>
		Public Shared Function CreateCategories(ByVal categoryID As Integer, ByVal categoryName As String) As Categories
			Dim categories As New Categories()
			categories.CategoryID = categoryID
			categories.CategoryName = categoryName
			Return categories
		End Function
		''' <summary>
		''' There are no comments for Property CategoryID in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty := True, IsNullable := False), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property CategoryID() As Integer
			Get
				Return Me._CategoryID
			End Get
			Set(ByVal value As Integer)
				Me.OnCategoryIDChanging(value)
				Me.ReportPropertyChanging("CategoryID")
				Me._CategoryID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("CategoryID")
				Me.OnCategoryIDChanged()
			End Set
		End Property
		Private _CategoryID As Integer
		Partial Private Sub OnCategoryIDChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnCategoryIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property CategoryName in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable := False), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property CategoryName() As String
			Get
				Return Me._CategoryName
			End Get
			Set(ByVal value As String)
				Me.OnCategoryNameChanging(value)
				Me.ReportPropertyChanging("CategoryName")
				Me._CategoryName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, False)
				Me.ReportPropertyChanged("CategoryName")
				Me.OnCategoryNameChanged()
			End Set
		End Property
		Private _CategoryName As String
		Partial Private Sub OnCategoryNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnCategoryNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Description in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Description() As String
			Get
				Return Me._Description
			End Get
			Set(ByVal value As String)
				Me.OnDescriptionChanging(value)
				Me.ReportPropertyChanging("Description")
				Me._Description = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("Description")
				Me.OnDescriptionChanged()
			End Set
		End Property
		Private _Description As String
		Partial Private Sub OnDescriptionChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnDescriptionChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property Picture in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Picture() As Byte()
			Get
				Return Global.System.Data.Objects.DataClasses.StructuralObject.GetValidValue(Me._Picture)
			End Get
			Set(ByVal value As Byte())
				Me.OnPictureChanging(value)
				Me.ReportPropertyChanging("Picture")
				Me._Picture = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("Picture")
				Me.OnPictureChanged()
			End Set
		End Property
		Private _Picture() As Byte
		Partial Private Sub OnPictureChanging(ByVal value() As Byte)
		End Sub
		Partial Private Sub OnPictureChanged()
		End Sub
		''' <summary>
		''' There are no comments for Products in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Products_Categories", "Products"), Global.System.Xml.Serialization.XmlIgnoreAttribute(), Global.System.Xml.Serialization.SoapIgnoreAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Products() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Products)
			Get
				Return (CType(Me, Global.System.Data.Objects.DataClasses.IEntityWithRelationships)).RelationshipManager.GetRelatedCollection(Of Products)("NorthwindModel.FK_Products_Categories", "Products")
			End Get
			Set(ByVal value As System.Data.Objects.DataClasses.EntityCollection(Of Products))
				If (value IsNot Nothing) Then
					CType(Me, Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Products)("NorthwindModel.FK_Products_Categories", "Products", value)
				End If
			End Set
		End Property
	End Class
	''' <summary>
	''' There are no comments for NorthwindModel.Products in the schema.
	''' </summary>
	''' <KeyProperties>
	''' ProductID
	''' </KeyProperties>
	<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName := "NorthwindModel", Name := "Products"), Global.System.Runtime.Serialization.DataContractAttribute(IsReference := True), Global.System.Serializable()> _
	Partial Public Class Products
		Inherits System.Data.Objects.DataClasses.EntityObject
		''' <summary>
		''' Create a new Products object.
		''' </summary>
		''' <param name="discontinued">Initial value of Discontinued.</param>
		''' <param name="productID">Initial value of ProductID.</param>
		''' <param name="productName">Initial value of ProductName.</param>
		Public Shared Function CreateProducts(ByVal discontinued As Boolean, ByVal productID As Integer, ByVal productName As String) As Products
			Dim products As New Products()
			products.Discontinued = discontinued
			products.ProductID = productID
			products.ProductName = productName
			Return products
		End Function
		''' <summary>
		''' There are no comments for Property Discontinued in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable := False), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Discontinued() As Boolean
			Get
				Return Me._Discontinued
			End Get
			Set(ByVal value As Boolean)
				Me.OnDiscontinuedChanging(value)
				Me.ReportPropertyChanging("Discontinued")
				Me._Discontinued = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("Discontinued")
				Me.OnDiscontinuedChanged()
			End Set
		End Property
		Private _Discontinued As Boolean
		Partial Private Sub OnDiscontinuedChanging(ByVal value As Boolean)
		End Sub
		Partial Private Sub OnDiscontinuedChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ProductID in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty := True, IsNullable := False), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property ProductID() As Integer
			Get
				Return Me._ProductID
			End Get
			Set(ByVal value As Integer)
				Me.OnProductIDChanging(value)
				Me.ReportPropertyChanging("ProductID")
				Me._ProductID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("ProductID")
				Me.OnProductIDChanged()
			End Set
		End Property
		Private _ProductID As Integer
		Partial Private Sub OnProductIDChanging(ByVal value As Integer)
		End Sub
		Partial Private Sub OnProductIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ProductName in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable := False), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property ProductName() As String
			Get
				Return Me._ProductName
			End Get
			Set(ByVal value As String)
				Me.OnProductNameChanging(value)
				Me.ReportPropertyChanging("ProductName")
				Me._ProductName = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, False)
				Me.ReportPropertyChanged("ProductName")
				Me.OnProductNameChanged()
			End Set
		End Property
		Private _ProductName As String
		Partial Private Sub OnProductNameChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnProductNameChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property QuantityPerUnit in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property QuantityPerUnit() As String
			Get
				Return Me._QuantityPerUnit
			End Get
			Set(ByVal value As String)
				Me.OnQuantityPerUnitChanging(value)
				Me.ReportPropertyChanging("QuantityPerUnit")
				Me._QuantityPerUnit = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, True)
				Me.ReportPropertyChanged("QuantityPerUnit")
				Me.OnQuantityPerUnitChanged()
			End Set
		End Property
		Private _QuantityPerUnit As String
		Partial Private Sub OnQuantityPerUnitChanging(ByVal value As String)
		End Sub
		Partial Private Sub OnQuantityPerUnitChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property ReorderLevel in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property ReorderLevel() As Global.System.Nullable(Of Short)
			Get
				Return Me._ReorderLevel
			End Get
			Set(ByVal value As System.Nullable(Of Short))
				Me.OnReorderLevelChanging(value)
				Me.ReportPropertyChanging("ReorderLevel")
				Me._ReorderLevel = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("ReorderLevel")
				Me.OnReorderLevelChanged()
			End Set
		End Property
		Private _ReorderLevel As Global.System.Nullable(Of Short)
		Partial Private Sub OnReorderLevelChanging(ByVal value As Global.System.Nullable(Of Short))
		End Sub
		Partial Private Sub OnReorderLevelChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property SupplierID in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property SupplierID() As Global.System.Nullable(Of Integer)
			Get
				Return Me._SupplierID
			End Get
			Set(ByVal value As System.Nullable(Of Integer))
				Me.OnSupplierIDChanging(value)
				Me.ReportPropertyChanging("SupplierID")
				Me._SupplierID = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("SupplierID")
				Me.OnSupplierIDChanged()
			End Set
		End Property
		Private _SupplierID As Global.System.Nullable(Of Integer)
		Partial Private Sub OnSupplierIDChanging(ByVal value As Global.System.Nullable(Of Integer))
		End Sub
		Partial Private Sub OnSupplierIDChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property UnitPrice in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property UnitPrice() As Global.System.Nullable(Of Decimal)
			Get
				Return Me._UnitPrice
			End Get
			Set(ByVal value As System.Nullable(Of Decimal))
				Me.OnUnitPriceChanging(value)
				Me.ReportPropertyChanging("UnitPrice")
				Me._UnitPrice = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("UnitPrice")
				Me.OnUnitPriceChanged()
			End Set
		End Property
		Private _UnitPrice As Global.System.Nullable(Of Decimal)
		Partial Private Sub OnUnitPriceChanging(ByVal value As Global.System.Nullable(Of Decimal))
		End Sub
		Partial Private Sub OnUnitPriceChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property UnitsInStock in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property UnitsInStock() As Global.System.Nullable(Of Short)
			Get
				Return Me._UnitsInStock
			End Get
			Set(ByVal value As System.Nullable(Of Short))
				Me.OnUnitsInStockChanging(value)
				Me.ReportPropertyChanging("UnitsInStock")
				Me._UnitsInStock = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("UnitsInStock")
				Me.OnUnitsInStockChanged()
			End Set
		End Property
		Private _UnitsInStock As Global.System.Nullable(Of Short)
		Partial Private Sub OnUnitsInStockChanging(ByVal value As Global.System.Nullable(Of Short))
		End Sub
		Partial Private Sub OnUnitsInStockChanged()
		End Sub
		''' <summary>
		''' There are no comments for Property UnitsOnOrder in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property UnitsOnOrder() As Global.System.Nullable(Of Short)
			Get
				Return Me._UnitsOnOrder
			End Get
			Set(ByVal value As System.Nullable(Of Short))
				Me.OnUnitsOnOrderChanging(value)
				Me.ReportPropertyChanging("UnitsOnOrder")
				Me._UnitsOnOrder = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
				Me.ReportPropertyChanged("UnitsOnOrder")
				Me.OnUnitsOnOrderChanged()
			End Set
		End Property
		Private _UnitsOnOrder As Global.System.Nullable(Of Short)
		Partial Private Sub OnUnitsOnOrderChanging(ByVal value As Global.System.Nullable(Of Short))
		End Sub
		Partial Private Sub OnUnitsOnOrderChanged()
		End Sub
		''' <summary>
		''' There are no comments for Categories in the schema.
		''' </summary>
		<Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("NorthwindModel", "FK_Products_Categories", "Categories"), Global.System.Xml.Serialization.XmlIgnoreAttribute(), Global.System.Xml.Serialization.SoapIgnoreAttribute(), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property Categories() As Categories
			Get
				Return (CType(Me, Global.System.Data.Objects.DataClasses.IEntityWithRelationships)).RelationshipManager.GetRelatedReference(Of Categories)("NorthwindModel.FK_Products_Categories", "Categories").Value
			End Get
			Set(ByVal value As Categories)
				CType(Me, Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Categories)("NorthwindModel.FK_Products_Categories", "Categories").Value = value
			End Set
		End Property
		''' <summary>
		''' There are no comments for Categories in the schema.
		''' </summary>
		<Global.System.ComponentModel.BrowsableAttribute(False), Global.System.Runtime.Serialization.DataMemberAttribute()> _
		Public Property CategoriesReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Categories)
			Get
				Return (CType(Me, Global.System.Data.Objects.DataClasses.IEntityWithRelationships)).RelationshipManager.GetRelatedReference(Of Categories)("NorthwindModel.FK_Products_Categories", "Categories")
			End Get
			Set(ByVal value As System.Data.Objects.DataClasses.EntityReference(Of Categories))
				If (value IsNot Nothing) Then
					CType(Me, Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Categories)("NorthwindModel.FK_Products_Categories", "Categories", value)
				End If
			End Set
		End Property
	End Class
End Namespace